# permissions for end users to edit nacos.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: nacos-editor-role
rules:
- apiGroups:
  - middleware.nacos.nancal
  resources:
  - nacos
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - middleware.nacos.nancal
  resources:
  - nacos/status
  verbs:
  - get
