---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - middleware.nacos.nancal
  resources:
  - nacos
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - middleware.nacos.nancal
  resources:
  - nacos/finalizers
  verbs:
  - update
- apiGroups:
  - middleware.nacos.nancal
  resources:
  - nacos/status
  verbs:
  - get
  - patch
  - update
