apiVersion: v1
kind: Service
metadata:
  labels:
    app: nacos
    component: nacos
    middleware: nacos
  name: nacos-nodeport
  namespace: default
spec:
  ports:
  - name: client
    port: 8848
    protocol: TCP
    targetPort: 8848
  - name: rpc
    port: 7848
    protocol: TCP
    targetPort: 7848
  - name: new-rpc
    port: 9848
    protocol: TCP
    targetPort: 9848
  publishNotReadyAddresses: true
  selector:
    app: nacos
    component: nacos
    middleware: nacos
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}

